### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by Rzero7** [RUCAIBox/RecBole-GNN#78]
您好，我在百度网盘中下载的的Yelp2018、Amazon-Book、Gowalla数据集都要比论文中所报告的统计数值大很多，请问怎么获得与论文中相同版本的数据集呢，十分感谢~

**Comment by ahukmr** [comment]
> 您好，我在百度网盘中下载的的Yelp2018、Amazon-Book、Gowalla数据集都要比论文中所报告的统计数值大很多，请问怎么获得与论文中相同版本的数据集呢，十分感谢~

同问，请问你这个问题解决了嘛？

**Comment by downeykking** [comment]
原始数据是没经过数据预处理的, 你可以写个dataset的yaml文件, 例如下面这个yelp.yaml文件
```
load_col:
  inter: [user_id, item_id, rating]
ITEM_ID_FIELD: item_id
RATING_FIELD: rating

user_inter_num_interval: "[15,inf)"
item_inter_num_interval: "[15,inf)"
val_interval:
  rating: "[3,inf)"
```
在执行的时候加上参数`--config_files`
```
python run_recbole_gnn.py --config_files=yelp.yaml
```
参数的具体含义可以参考文档: https://recbole.io/docs/user_guide/config/data_settings.html
